-- �Զ���type
INSERT INTO Types 
		(Type, Kind)
VALUES	
		('MODIFIER_MAGICPOT_CAPITAL_CITY_GRANT_BUILDING_IN_CITY','KIND_MODIFIER'),
		('MODIFIER_PAIMEI_CAPITAL_CITY_GRANT_UNIT_IN_CITY', 'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
		(ModifierType, CollectionType, EffectType)
VALUES	
		('MODIFIER_MAGICPOT_CAPITAL_CITY_GRANT_BUILDING_IN_CITY','COLLECTION_PLAYER_CAPITAL_CITY','EFFECT_GRANT_BUILDING_IN_CITY'),
		('MODIFIER_PAIMEI_CAPITAL_CITY_GRANT_UNIT_IN_CITY', 'COLLECTION_PLAYER_CAPITAL_CITY','EFFECT_GRANT_UNIT_IN_CITY');

INSERT INTO Modifiers 
		(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES	
		('LEADER_PAIMEI_SEND_MAGICPOT','MODIFIER_MAGICPOT_CAPITAL_CITY_GRANT_BUILDING_IN_CITY',NULL),
		('LEADER_PAIMEI_SEND_PAIMEI', 'MODIFIER_PAIMEI_CAPITAL_CITY_GRANT_UNIT_IN_CITY', NULL);

INSERT INTO ModifierArguments
		(ModifierId, Name, Value)
VALUES	
		('LEADER_PAIMEI_SEND_MAGICPOT', 'BuildingType', 'BUILDING_MAGICPOT'),
		('LEADER_PAIMEI_SEND_MAGICPOT', 'Amount', 1),
		('LEADER_PAIMEI_SEND_PAIMEI', 'UnitType', 'UNIT_PAIMEI'),
		('LEADER_PAIMEI_SEND_PAIMEI', 'Amount', 1);

INSERT INTO BuildingModifiers
		(BuildingType, ModifierId)
VALUES	
		('BUILDING_PALACE',	'LEADER_PAIMEI_SEND_MAGICPOT'),
		('BUILDING_PALACE',	'LEADER_PAIMEI_SEND_PAIMEI');

--Unit PAIMEI
-- ��ݮ�Ķ���������

INSERT INTO Modifiers 
		(ModifierId, ModifierType, Permanent, SubjectRequirementSetId)
VALUES	
		--�������к;�ӪʱԶ�̹���Ч��Ϊ100%
		('UNIT_PAIMEI_IGNORE_RANGED_VS_DISTRICT_PENALTY', 'MODIFIER_PLAYER_UNIT_IGNORE_RANGED_VS_DISTRICT_PENALTY', 1, NULL),
		--��߶Դ��ģɱ����������
		('PAIMEI_GDR_WMD_RESISTANCE','MODIFIER_PLAYER_UNIT_ADJUST_WMD_RESISTANCE', 1, NULL),
		--������ݮ�ķ�����
		('UNIT_PAIMEI_GDR_ARMOR_DEFENSES','MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',1,'UNIT_PAIMEI_GDR_DEFENSE_UPGRADE_REQUIREMENTS'),
		--��ס��
		('LEADER_PAIMEI_CITIES_ADJUST_BUILDING_HOUSING', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING', 1, NULL),
		--���˿�
		('LEADER_PAIMEI_CITIES_ADD_POPULATION', 'MODIFIER_PLAYER_CITIES_ADD_POPULATION', 1, NULL),
		--��ǿ��ǽ����
		('LEADER_PAIMEI_CITY_GRANT_CITIES_URBAN_DEFENSES', 'MODIFIER_PLAYER_GRANT_CITIES_URBAN_DEFENSES', 1, NULL),
		--��Զ�̹�����Χ
		('UNIT_PAIMEI_ATTACK_RANGE_1', 'MODIFIER_UNIT_ADJUST_ATTACK_RANGE', 1, NULL),
		--�������
		('UNIT_PAIMEI_BONUS_1', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 1, NULL),
		('UNIT_PAIMEI_BONUS_2', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 1, NULL),
		('UNIT_PAIMEI_BONUS_3', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 1, NULL),
		('UNIT_PAIMEI_BONUS_4', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 1, NULL),
		('UNIT_PAIMEI_BONUS_5', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 1, NULL),	
		('UNIT_PAIMEI_BONUS_6', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 1, NULL),	
		('UNIT_PAIMEI_BONUS_7', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 1, NULL),
		--ȫ�����
		('UNIT_all_BONUS_1', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 1, NULL),
		--ȫ�������
		('UNIT_all_MOVEMENT_1','MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 1, NULL),
		--���������
		('UNIT_PAIMEI_MOVEMENT_1','MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 1, NULL),
		('UNIT_PAIMEI_MOVEMENT_2','MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 1, NULL),
		('UNIT_PAIMEI_MOVEMENT_3','MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 1, NULL),
		('UNIT_PAIMEI_MOVEMENT_4','MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 1, NULL),
		--����������ƶ�
		('UNIT_PAIMEI_ADJUST_ATTACK_AND_MOVE', 'MODIFIER_PLAYER_UNIT_ADJUST_ATTACK_AND_MOVE', 0, NULL),
		('UNIT_PAIMEI_2_1_1', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 1, NULL),
		('UNIT_PAIMEI_2_1_2', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 1, NULL),
		('UNIT_PAIMEI_3_3_1', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 1, NULL),
		--���ӽ�����ʹ�ô���
		('UNIT_PAIMEI_ADJUST_BUILDER_CHARGES', 'MODIFIER_PLAYER_UNITS_ADJUST_BUILDER_CHARGES', 1, NULL),
		--���ӳ���������
		('LEADER_PAIMEI_CITY_ADJUST_CITY_YIELD_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 1, NULL),
		('UNIT_PAIMEI_ADJUST_NUM_ATTACKS', 'MODIFIER_UNIT_ADJUST_NUM_ATTACKS', 1, NULL);

INSERT INTO ModifierArguments
		(ModifierId, Name, Value)
VALUES	
		('UNIT_PAIMEI_IGNORE_RANGED_VS_DISTRICT_PENALTY', 'Ignore', 1),

		('PAIMEI_GDR_WMD_RESISTANCE', 'Blast', 1),
		('PAIMEI_GDR_WMD_RESISTANCE', 'Fallout', 100),
		
		('UNIT_PAIMEI_GDR_ARMOR_DEFENSES', 'Amount', 10),

		('LEADER_PAIMEI_CITY_GRANT_CITIES_URBAN_DEFENSES', 'DefenseValue', 200),
		('UNIT_PAIMEI_ATTACK_RANGE_1', 'Amount', 1),
		('LEADER_PAIMEI_CITIES_ADD_POPULATION', 'Amount', 1),
		('LEADER_PAIMEI_CITIES_ADJUST_BUILDING_HOUSING', 'Amount', 1),

		('UNIT_PAIMEI_BONUS_1', 'Amount', 5),
		('UNIT_PAIMEI_BONUS_2', 'Amount', 10),
		('UNIT_PAIMEI_BONUS_3', 'Amount', 10),
		('UNIT_PAIMEI_BONUS_4', 'Amount', 10),
		('UNIT_PAIMEI_BONUS_5', 'Amount', 15),
		('UNIT_PAIMEI_BONUS_6', 'Amount', 10),
		('UNIT_PAIMEI_BONUS_7', 'Amount', 20),

		('UNIT_PAIMEI_MOVEMENT_1','Amount',1),
		('UNIT_PAIMEI_MOVEMENT_2','Amount',2),
		('UNIT_PAIMEI_MOVEMENT_3','Amount',3),
		('UNIT_PAIMEI_MOVEMENT_4','Amount',3),
		
		('UNIT_all_BONUS_1', 'Amount', 5),
		('UNIT_all_MOVEMENT_1', 'Amount', 1),
		
		('UNIT_PAIMEI_ADJUST_ATTACK_AND_MOVE', 'CanMove', 1),
		('UNIT_PAIMEI_ADJUST_BUILDER_CHARGES', 'Amount', 1),
		
		('LEADER_PAIMEI_CITY_ADJUST_CITY_YIELD_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
		('LEADER_PAIMEI_CITY_ADJUST_CITY_YIELD_PRODUCTION', 'Amount', 10),
		('UNIT_PAIMEI_ADJUST_NUM_ATTACKS', 'Amount', 1);

INSERT INTO UnitPromotionModifiers
		(UnitPromotionType, ModifierId)
VALUES
		-- L1_1 ����ҩ�����ƶ���+1
		('PROMOTION_PAIMEI_L1_1', 'UNIT_PAIMEI_MOVEMENT_1'),
		-- L1_2 ��ɽ���У�����+5
		('PROMOTION_PAIMEI_L1_2', 'UNIT_PAIMEI_BONUS_1'),
		-- ���� ��³���ıӻ������磩������+20��������+10%
		('PROMOTION_PAIMEI_L1_3', 'UNIT_PAIMEI_BONUS_2'),
		('PROMOTION_PAIMEI_L1_3', 'UNIT_PAIMEI_BONUS_3'),
		('PROMOTION_PAIMEI_L1_3', 'LEADER_PAIMEI_CITY_ADJUST_CITY_YIELD_PRODUCTION'),
		-- L2_3 ӽ�����������+1���Գ���Զ��Ч��100%
		('PROMOTION_PAIMEI_L2_3', 'UNIT_PAIMEI_ATTACK_RANGE_1'),
		('PROMOTION_PAIMEI_L2_3', 'UNIT_PAIMEI_IGNORE_RANGED_VS_DISTRICT_PENALTY'),
		-- L2_2 ħ�����ܣ���������+10�����г�ǽ����+200
		('PROMOTION_PAIMEI_L2_2', 'UNIT_PAIMEI_GDR_ARMOR_DEFENSES'),
		('PROMOTION_PAIMEI_L2_2', 'LEADER_PAIMEI_CITY_GRANT_CITIES_URBAN_DEFENSES'),
		-- ���� ������µıӻ���������������+10��ȫ���ƶ���+1��������+10%
		('PROMOTION_PAIMEI_L2_1', 'UNIT_PAIMEI_BONUS_4'),
		('PROMOTION_PAIMEI_L2_1', 'UNIT_all_MOVEMENT_1'),
		('PROMOTION_PAIMEI_L2_1', 'LEADER_PAIMEI_CITY_ADJUST_CITY_YIELD_PRODUCTION'),
		-- ���� ����˹�ϵıӻ������������˿�+1��ס��+1�������ߴ���+1��������+10%
		('PROMOTION_PAIMEI_L3_1', 'LEADER_PAIMEI_CITIES_ADD_POPULATION'),
		('PROMOTION_PAIMEI_L3_1', 'LEADER_PAIMEI_CITIES_ADJUST_BUILDING_HOUSING'),
		('PROMOTION_PAIMEI_L3_1', 'UNIT_PAIMEI_ADJUST_BUILDER_CHARGES'),
		('PROMOTION_PAIMEI_L3_1', 'LEADER_PAIMEI_CITY_ADJUST_CITY_YIELD_PRODUCTION'),
		-- L3_2 ��������⣺����+25��ȫ������+5
		('PROMOTION_PAIMEI_L3_2', 'UNIT_PAIMEI_BONUS_5'),
		('PROMOTION_PAIMEI_L3_2', 'UNIT_PAIMEI_BONUS_6'),
		('PROMOTION_PAIMEI_L3_2', 'UNIT_all_BONUS_1'),
		-- L3_3 ����¬�ˣ��ƶ���+2
		('PROMOTION_PAIMEI_L3_3', 'UNIT_PAIMEI_MOVEMENT_2'),
		-- ���� ���ٵıӻ���������������+20�����⹥��һ�Ρ���������ƶ������ģɱ�������߿��ԡ�������+5%
		('PROMOTION_PAIMEI_L4', 'UNIT_PAIMEI_BONUS_7'),
		('PROMOTION_PAIMEI_L4', 'UNIT_PAIMEI_ADJUST_NUM_ATTACKS'),
		('PROMOTION_PAIMEI_L4', 'UNIT_PAIMEI_ADJUST_ATTACK_AND_MOVE'),
		('PROMOTION_PAIMEI_L4', 'PAIMEI_GDR_WMD_RESISTANCE'),
		('PROMOTION_PAIMEI_L4', 'LEADER_PAIMEI_CITY_ADJUST_CITY_YIELD_PRODUCTION');

INSERT INTO Modifiers 
		(ModifierId, ModifierType)
VALUES	
		('PAIMEI_IGNOREZOC_IGNORE_ZOC','MODIFIER_PLAYER_UNIT_ADJUST_IGNORE_ZOC'),
		('PAIMEI_GDR_FIGHT_WHILE_EMBARKED','MODIFIER_SINGLE_UNIT_ADJUST_FIGHT_WHILE_EMBARKED');

INSERT INTO ModifierArguments
		(ModifierId, Name, Value)
VALUES
		('PAIMEI_IGNOREZOC_IGNORE_ZOC','Ignore', 1),
		('PAIMEI_GDR_FIGHT_WHILE_EMBARKED','CanFight', 1);

INSERT INTO UnitAbilityModifiers
		(UnitAbilityType, ModifierId)
VALUES	
		--('ABILITY_PAIMEI', 'PAIMEI_GDR_WMD_RESISTANCE'),
		('ABILITY_PAIMEI', 'PAIMEI_IGNOREZOC_IGNORE_ZOC'),
		('ABILITY_PAIMEI', 'PAIMEI_GDR_FIGHT_WHILE_EMBARKED');

-- ��ݮ�����޸������޽��ĸ�����ʩ
INSERT INTO Improvement_ValidBuildUnits
				(ImprovementType, UnitType)
SELECT ImprovementType, 'UNIT_PAIMEI'
FROM Improvement_ValidBuildUnits WHERE UnitType = 'UNIT_BUILDER';

--��ĿЧ��
INSERT INTO ProjectCompletionModifiers (ProjectType, ModifierId) values
	('PROJECT_PRIMARY_PAIMEI_ADJUST_MOVEMENT', 'MODIFIER_PROJECT_PRIMARY_PAIMEI_ADJUST_MOVEMENT'),
	('PROJECT_PRIMARY_PAIMEI_ADJUST_COMBAT_STRENGTH', 'MODIFIER_PROJECT_PRIMARY_PAIMEI_ADJUST_COMBAT_STRENGTH'),
	('PROJECT_INTER_PAIMEI_ADJUST_MOVEMENT', 'MODIFIER_PROJECT_INTER_PAIMEI_ADJUST_MOVEMENT'),
	('PROJECT_INTER_PAIMEI_ADJUST_COMBAT_STRENGTH', 'MODIFIER_PROJECT_INTER_PAIMEI_ADJUST_COMBAT_STRENGTH'),
	('PROJECT_ADVANCED_PAIMEI_ADJUST_MOVEMENT', 'MODIFIER_PROJECT_ADVANCED_PAIMEI_ADJUST_MOVEMENT'),
	('PROJECT_ADVANCED_PAIMEI_ADJUST_COMBAT_STRENGTH', 'MODIFIER_PROJECT_ADVANCED_PAIMEI_ADJUST_COMBAT_STRENGTH');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) values
	('MODIFIER_PROJECT_PRIMARY_PAIMEI_ADJUST_MOVEMENT', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 'REQSET_PAIMEI'),
	('MODIFIER_PROJECT_PRIMARY_PAIMEI_ADJUST_COMBAT_STRENGTH', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 'REQSET_PAIMEI'),
	('MODIFIER_PROJECT_INTER_PAIMEI_ADJUST_MOVEMENT', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 'REQSET_PAIMEI'),
	('MODIFIER_PROJECT_INTER_PAIMEI_ADJUST_COMBAT_STRENGTH', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 'REQSET_PAIMEI'),
	('MODIFIER_PROJECT_ADVANCED_PAIMEI_ADJUST_MOVEMENT', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 'REQSET_PAIMEI'),
	('MODIFIER_PROJECT_ADVANCED_PAIMEI_ADJUST_COMBAT_STRENGTH', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 'REQSET_PAIMEI');

INSERT INTO ModifierArguments
		(ModifierId, Name, Value)
VALUES	
		('MODIFIER_PROJECT_PRIMARY_PAIMEI_ADJUST_MOVEMENT', 'Amount', 1),
		('MODIFIER_PROJECT_PRIMARY_PAIMEI_ADJUST_COMBAT_STRENGTH', 'Amount', 1),
		('MODIFIER_PROJECT_INTER_PAIMEI_ADJUST_MOVEMENT', 'Amount', 2),
		('MODIFIER_PROJECT_INTER_PAIMEI_ADJUST_COMBAT_STRENGTH', 'Amount', 3),
		('MODIFIER_PROJECT_ADVANCED_PAIMEI_ADJUST_MOVEMENT', 'Amount', 3),
		('MODIFIER_PROJECT_ADVANCED_PAIMEI_ADJUST_COMBAT_STRENGTH', 'Amount', 5);
--���е�λפ���ڳ���ʱProject��100%������
--INSERT INTO BuildingModifiers
		--(BuildingType, ModifierId)
--VALUES	
		--('BUILDING_MAGICPOT',	'PROJECT_PAIMEI_ADJUST_MOVEMENT_ADJUST_PRODUCTION');
--INSERT INTO Modifiers 
		--(ModifierId, ModifierType, SubjectRequirementSetId)
--VALUES	
		--('PROJECT_PAIMEI_ADJUST_MOVEMENT_ADJUST_PRODUCTION','MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'REQSET_PROJECT');
--INSERT INTO ModifierArguments
		--(ModifierId, Name, Value)
--VALUES
		--('PROJECT_PAIMEI_ADJUST_MOVEMENT_ADJUST_PRODUCTION','ProjectType','PROJECT_PAIMEI_ADJUST_MOVEMENT'),
		--('PROJECT_PAIMEI_ADJUST_MOVEMENT_ADJUST_PRODUCTION','Amount', -100);
--INSERT INTO RequirementSets 
		--(RequirementSetId, RequirementSetType)
--VALUES	
		--('REQSET_PROJECT', 'REQUIREMENTSET_TEST_ALL');
--INSERT INTO Requirements 
		--(RequirementId, RequirementType, Inverse)
--VALUES	
		--('REQSET_GARRISON_UNIT', 'REQUIREMENT_CITY_HAS_GARRISON_UNIT', 1);
		----('REQSET_PAIMEI_1', 'REQUIREMENT_UNIT_TYPE_MATCHES', 0);
--
--INSERT INTO RequirementSetRequirements
		--(RequirementSetId, RequirementId)
--VALUES	
		--('REQSET_PROJECT', 'REQSET_GARRISON_UNIT');
		--('REQSET_PROJECT', 'REQSET_PAIMEI_1');

--INSERT INTO RequirementArguments
		--(RequirementId, Name, Value)
--VALUES	
		--('REQSET_PAIMEI_1', 'UnitType', 'UNIT_PAIMEI');
--REQ
--������ݮ��Ч
INSERT INTO RequirementSets 
		(RequirementSetId, RequirementSetType)
VALUES	
		('REQSET_PAIMEI', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO Requirements 
		(RequirementId, RequirementType)
VALUES	
		('REQSET_PAIMEI', 'REQUIREMENT_UNIT_TYPE_MATCHES');

INSERT INTO RequirementSetRequirements
		(RequirementSetId, RequirementId)
VALUES	
		('REQSET_PAIMEI', 'REQSET_PAIMEI');

INSERT INTO RequirementArguments
		(RequirementId, Name, Value)
VALUES	
		('REQSET_PAIMEI', 'UnitType', 'UNIT_PAIMEI');

--���Է���ʱ��Ч
INSERT INTO RequirementSets 
		(RequirementSetId, RequirementSetType)
VALUES	
		('UNIT_PAIMEI_GDR_DEFENSE_UPGRADE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO Requirements 
		(RequirementId, RequirementType, Inverse)
VALUES	
		('UNIT_PAIMEI_GDR_DEFENSE_UPGRADE_REQUIREMENTS', 'REQUIREMENT_PLAYER_IS_ATTACKING', 1);

INSERT INTO RequirementSetRequirements
		(RequirementSetId, RequirementId)
VALUES	
		('UNIT_PAIMEI_GDR_DEFENSE_UPGRADE_REQUIREMENTS', 'UNIT_PAIMEI_GDR_DEFENSE_UPGRADE_REQUIREMENTS');


------ REQ
----INSERT INTO RequirementSets 
		----(RequirementSetId, RequirementSetType)
----VALUES	
		----('REQSET_UNIT_ADJ_PAIMEI', 'REQUIREMENTSET_TEST_ALL'),
		----('REQSET_MELEE_OPPONENT', 'REQUIREMENTSET_TEST_ALL'),
		----('REQSET_PAIMEI_IN_FOREST', 'REQUIREMENTSET_TEST_ALL'),
		----('REQSET_PAIMEI_IN_RAIN_FOREST', 'REQUIREMENTSET_TEST_ALL'),	
		----('REQSET_UNIT_IS_PAIMEI', 'REQUIREMENTSET_TEST_ALL');
----
----INSERT INTO Requirements 
		----(RequirementId, RequirementType)
----VALUES	
		----('REQ_UNIT_ADJ_PAIMEI', 'REQUIREMENT_PLOT_ADJACENT_FRIENDLY_UNIT_TYPE_MATCHES'), 
		----('REQ_MELEE_OPPONENT', 'REQUIREMENT_OPPONENT_UNIT_TAG_MATCHES'), 
		----('REQ_PAIMEI_IN_FOREST', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'), 
		----('REQ_PAIMEI_IN_RAIN_FOREST', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'), 
		----('REQ_UNIT_IS_PAIMEI', 'REQUIREMENT_UNIT_TYPE_MATCHES');
----
----INSERT INTO RequirementSetRequirements
		----(RequirementSetId, RequirementId)
----VALUES	
		----('REQSET_UNIT_ADJ_PAIMEI', 'REQ_UNIT_ADJ_PAIMEI'),
		----('REQSET_MELEE_OPPONENT', 'REQ_MELEE_OPPONENT'),
		----('REQSET_PAIMEI_IN_FOREST', 'REQ_PAIMEI_IN_FOREST'),
		----('REQSET_PAIMEI_IN_RAIN_FOREST', 'REQ_PAIMEI_IN_RAIN_FOREST'),
		----('REQSET_UNIT_IS_PAIMEI', 'REQ_UNIT_IS_PAIMEI');
----
----
----INSERT INTO RequirementArguments
		----(RequirementId, Name, Value)
----VALUES	
		----('REQ_UNIT_ADJ_PAIMEI', 'UnitType', 'UNIT_PAIMEI'),
		----('REQ_MELEE_OPPONENT', 'Tag', 'CLASS_MELEE'),
		----('REQ_PAIMEI_IN_FOREST', 'FeatureType', 'FEATURE_FOREST'),
		----('REQ_PAIMEI_IN_RAIN_FOREST', 'FeatureType', 'FEATURE_JUNGLE'), 
		----('REQ_UNIT_IS_PAIMEI', 'UnitType', 'UNIT_PAIMEI');
----
----
----INSERT INTO Modifiers 
		----(ModifierId, ModifierType, SubjectRequirementSetId)
----VALUES	('TRAIT_PAIMEI_WONDER_PERCENT', 'MODIFIER_PLAYER_ADJUST_UNIT_WONDER_PERCENT', NULL) ,
		----('TRAIT_PAIMEI_DISTRICT_PERCENT', 'MODIFIER_PLAYER_ADJUST_UNIT_DISTRICT_PERCENT', NULL) ,
		----('TRAIT_PAIMEI_VS_MELEE_BONUS_MODIFIER', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'REQSET_MELEE_OPPONENT') ,
		----('TRAIT_PAIMEI_VS_MELEE_BONUS', 'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER', NULL) ,
		----('TRAIT_PAIMEI_SIEGE_BONUS_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_SUPPORT_BONUS_MODIFIER', NULL) ,
		----('TRAIT_PAIMEI_SIEGE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL) ,
		----('PAIMEI_IN_FORMATION_BONUS_MOVEMENT', 'MODIFIER_PAIMEI_ADJUST_FRIENDLY_TERRITORY_START_MOVEMENT', NULL) ,
		----('PAIMEI_BONUS_IN_FOREST', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'REQSET_PAIMEI_IN_FOREST') ,
		----('PAIMEI_BONUS_IN_RAIN_FOREST', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'REQSET_PAIMEI_IN_RAIN_FOREST') ,
		----('PAIMEI_KILL_MACHINE', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL) ,
		----('PAIMEI_LV_UP_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL) ,
		----('PAIMEI_VS_DISTRICT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'BOMBARDMENT_REQUIREMENTS') ,
		----('TRAIT_PAIMEI_FASTER_COMBAT_XP', 'MODIFIER_PLAYER_UNIT_ADJUST_UNIT_EXPERIENCE_MODIFIER', NULL) ,
		----('TRAIT_PAIMEI_NEIGHBOR_COMBAT_MODIFIER', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL) ,
		----('TRAIT_PAIMEI_NEIGHBOR_COMBAT', 'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER', 'REQSET_UNIT_ADJ_PAIMEI') ;
----
----
----INSERT INTO ModifierArguments
		----(ModifierId, Name, Value)
----VALUES	('TRAIT_PAIMEI_WONDER_PERCENT', 'Amount', 5),
		----('TRAIT_PAIMEI_DISTRICT_PERCENT', 'Amount', 5) ,
		----('TRAIT_PAIMEI_VS_MELEE_BONUS_MODIFIER', 'Amount', 10),
		----('TRAIT_PAIMEI_VS_MELEE_BONUS', 'ModifierId', 'TRAIT_PAIMEI_VS_MELEE_BONUS_MODIFIER'),
		----('TRAIT_PAIMEI_SIEGE_BONUS_MODIFIER', 'Amount', 100) ,
		----('TRAIT_PAIMEI_SIEGE_BONUS', 'ModifierId', 'TRAIT_PAIMEI_SIEGE_BONUS_MODIFIER') ,
		----('PAIMEI_IN_FORMATION_BONUS_MOVEMENT', 'Amount', 1) ,
		----('PAIMEI_BONUS_IN_FOREST', 'Amount', 10) ,
		----('PAIMEI_BONUS_IN_RAIN_FOREST', 'Amount', 10) ,
		----('PAIMEI_KILL_MACHINE', 'Amount', 10) ,
		----('PAIMEI_LV_UP_BONUS', 'Amount', 5) ,
		----('PAIMEI_VS_DISTRICT_BONUS', 'Amount', -10) ,
		----('TRAIT_PAIMEI_FASTER_COMBAT_XP', 'Amount', 25) ,
		----('TRAIT_PAIMEI_NEIGHBOR_COMBAT_MODIFIER', 'Amount', 10),
		----('TRAIT_PAIMEI_NEIGHBOR_COMBAT', 'ModifierId', 'TRAIT_PAIMEI_NEIGHBOR_COMBAT_MODIFIER');
----
----INSERT INTO UnitAbilityModifiers
		----(UnitAbilityType, ModifierId)
----VALUES	('ABILITY_PAIMEI', 'PAIMEI_VS_DISTRICT_BONUS');
----
------ ��ݮ�Ķ���������
----INSERT INTO UnitPromotionModifiers 
		----(UnitPromotionType, ModifierId)
----VALUES	('PROMOTION_PAIMEI_L1L', 'DOUBLE_ENVELOPMENT_BONUS_FLANKING_BONUS_MODIFIER') ,
		----('PROMOTION_PAIMEI_L1L', 'TRAIT_PAIMEI_SIEGE_BONUS') ,
		----('PROMOTION_PAIMEI_L2L', 'DANCING_CRANE_BONUS_MOVEMENT') ,
		----('PROMOTION_PAIMEI_L3L', 'CAMOUFLAGE_STEALTH') ,
		----('PROMOTION_PAIMEI_L3L', 'PAIMEI_BONUS_IN_FOREST') ,
		----('PROMOTION_PAIMEI_L3L', 'PAIMEI_BONUS_IN_RAIN_FOREST') ,
		----('PROMOTION_PAIMEI_L1R', 'TRAIT_PAIMEI_NEIGHBOR_COMBAT') ,
		----('PROMOTION_PAIMEI_L2R', 'PAIMEI_IN_FORMATION_BONUS_MOVEMENT') ,
		----('PROMOTION_PAIMEI_L2R', 'ESCORT_MOBILITY_SHARED_MOVEMENT') ,
		----('PROMOTION_PAIMEI_L3R', 'ELITE_GUARD_ADDITIONAL_ATTACK') ,
		----('PROMOTION_PAIMEI_L3R', 'MOD_MOVE_AFTER_ATTACKING') ,
		----('PROMOTION_PAIMEI_L4', 'IGNOREZOC_IGNORE_ZOC') ,
		----('PROMOTION_PAIMEI_L4', 'PAIMEI_KILL_MACHINE') , 
		----('PROMOTION_PAIMEI_L1L', 'PAIMEI_LV_UP_BONUS') ,
		----('PROMOTION_PAIMEI_L2L', 'PAIMEI_LV_UP_BONUS') ,
		----('PROMOTION_PAIMEI_L3L', 'PAIMEI_LV_UP_BONUS') ,
		----('PROMOTION_PAIMEI_L1R', 'PAIMEI_LV_UP_BONUS') ,
		----('PROMOTION_PAIMEI_L2R', 'PAIMEI_LV_UP_BONUS') ,
		----('PROMOTION_PAIMEI_L3R', 'PAIMEI_LV_UP_BONUS') ,
		----('PROMOTION_PAIMEI_L4', 'PAIMEI_LV_UP_BONUS') ;
--
---- Leader PAIMEI
--
----INSERT INTO Modifiers 
----		(ModifierId, ModifierType, SubjectRequirementSetId)
----VALUES	
----		('LEADER_PAIMEI_SEND_PAIMEI', 'MODIFIER_PAIMEI_PLAYER_CITIES_GRANT_UNIT', NULL);
 --INSERT INTO Modifiers 
		--(ModifierId, ModifierType, SubjectRequirementSetId)
--VALUES	
		--('LEADER_PAIMEI_SEND_PAIMEI', 'MODIFIER_PAIMEI_CAPITAL_CITY_GRANT_UNIT_IN_CITY', NULL);
--
--INSERT INTO ModifierArguments
		--(ModifierId, Name, Value)
--VALUES	
		--('LEADER_PAIMEI_SEND_PAIMEI', 'UnitType', 'UNIT_PAIMEI'),
		--('LEADER_PAIMEI_SEND_PAIMEI', 'Amount', 1);
--
--INSERT INTO TraitModifiers
		--(TraitType, ModifierId)
--VALUES	
		--('LEADER_PAIMEI',	'LEADER_PAIMEI_SEND_PAIMEI');
--
--
-- ============ 文明单位经验加成：升级所需经验 晋升等级×15 → 晋升等级×10 ============
-- 经验获取 +50%（MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER，原版罗斯福"野马"同款效果）：
-- 获取×1.5 等价于需求×2/3，对每一级都精确成立（15×N ÷ 1.5 = 10×N），任何游戏速度下均适用
INSERT OR REPLACE INTO Modifiers
	(ModifierId, ModifierType, RunOnce, Permanent)
VALUES
	('MODIFIER_WITCHSPRING_XP_BOOST', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', 0, 1);

INSERT OR REPLACE INTO ModifierArguments
	(ModifierId, Name, Value)
VALUES
	('MODIFIER_WITCHSPRING_XP_BOOST', 'Amount', 50);

INSERT OR REPLACE INTO TraitModifiers
	(TraitType, ModifierId)
VALUES
	('TRAIT_BUILDING_MAGICPOT', 'MODIFIER_WITCHSPRING_XP_BOOST');
-- ============ 文明特性：建立宗教的国家向本文明宣战时，所有城市 +100% 生产力，持续 10 回合 ============
-- 参考澳大利亚 TRAIT_CITADELCIVILIZATION_DEFENSIVE_PRODUCTION；SubjectRequirementSetId 限定宣战方已建立宗教
INSERT OR REPLACE INTO Modifiers
	(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES
	('MODIFIER_WITCHSPRING_RELIGIOUS_WAR_PRODUCTION', 'MODIFIER_PLAYER_ADD_DIPLOMATIC_YIELD_MODIFIER', 'PLAYER_FOUNDED_RELIGION_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments
	(ModifierId, Name, Value)
VALUES
	('MODIFIER_WITCHSPRING_RELIGIOUS_WAR_PRODUCTION', 'DiplomaticYieldSource', 'WAR_DECLARATION_RECEIVED'),
	('MODIFIER_WITCHSPRING_RELIGIOUS_WAR_PRODUCTION', 'TurnsActive', 10),
	('MODIFIER_WITCHSPRING_RELIGIOUS_WAR_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
	('MODIFIER_WITCHSPRING_RELIGIOUS_WAR_PRODUCTION', 'Amount', 100);

INSERT OR REPLACE INTO TraitModifiers
	(TraitType, ModifierId)
VALUES
	('TRAIT_BUILDING_MAGICPOT', 'MODIFIER_WITCHSPRING_RELIGIOUS_WAR_PRODUCTION');
